'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { escapeHTML } = require('hexo-util');

// Ship the exact fonts/CSS belonging to the build-time KaTeX renderer.
hexo.extend.generator.register('local-katex-assets', () => {
  const katexRoot = path.dirname(require.resolve('katex/package.json', {
    paths: [path.dirname(require.resolve('@traptitech/markdown-it-katex'))]
  }));
  const dist = path.join(katexRoot, 'dist');
  const files = ['katex.min.css', ...fs.readdirSync(path.join(dist, 'fonts')).map(name => `fonts/${name}`)];
  return files.map(file => ({
    path: `vendor/katex/${file}`,
    data: () => fs.createReadStream(path.join(dist, file))
  }));
});

// External services stay disabled until the site's own public IDs are supplied.
hexo.extend.filter.register('before_generate', () => {
  if (hexo.config.theme !== 'butterfly') return;
  const theme = hexo.theme.config;
  const endpoint = process.env.TWIKOO_ENV_ID || theme.twikoo.envId;
  if (endpoint) {
    if (!/^https:\/\/[^\s'"<>]+$/.test(endpoint)) throw new Error('Twikoo requires a valid HTTPS endpoint.');
    theme.twikoo.envId = endpoint;
    theme.comments.use = ['Twikoo'];
  }

  const footerParts = [];
  if (theme.footer.launch_at) {
    const launchedAt = new Date(theme.footer.launch_at);
    if (Number.isNaN(launchedAt.getTime())) throw new Error('Use an ISO timestamp with timezone for footer.launch_at.');
    const iso = launchedAt.toISOString();
    footerParts.push(`<div class="site-journey" data-launch-at="${iso}"><p class="site-runtime" hidden>已航行 <span data-runtime role="timer" aria-live="off"></span></p></div>`);
  }

  const scriptUrl = process.env.VISITOR_MAP_SCRIPT_URL || theme.visitor_map.script_url;
  if (scriptUrl) {
    const url = new URL(scriptUrl);
    if (url.protocol !== 'https:' || url.hostname !== 'mapmyvisitors.com' || !/^\/(map|globe)(_[\w-]+)?\.js$/.test(url.pathname)) {
      throw new Error('Use the HTTPS embed script URL generated by MapMyVisitors.');
    }
    const scriptId = url.pathname.startsWith('/globe') ? 'mmvst_globe' : 'mmvst_map';
    footerParts.push(`<section class="visitor-map" aria-label="访客来源地图"><h2>读者来自哪里</h2><script async id="${scriptId}" src="${escapeHTML(url.href)}"></script><p>自启用日起记录的访客大致来源</p></section>`);
  }
  if (footerParts.length) theme.footer.custom_text = footerParts.join('');
}, 20);
